complete -c ffuf -f

# HTTP OPTIONS
complete -c ffuf -o H -d 'Header "Name: Value" (separated by colon)'
complete -c ffuf -o X -d 'HTTP method to use'
complete -c ffuf -o b -d 'Cookie data "NAME1=VALUE1; NAME2=VALUE2" for copy as curl functionality'
complete -c ffuf -o cc -d 'Client cert for authentication. Client key needs to be defined as well for this to work'
complete -c ffuf -o ck -d 'Client key for authentication. Client certificate needs to be defined as well for this to work'
complete -c ffuf -o d -d 'POST data'
complete -c ffuf -o http2 -d 'Use HTTP2 protocol'
complete -c ffuf -o ignore-body -d 'Do not fetch the response content'
complete -c ffuf -o postflight -d 'Raw HTTP request file to run after each fuzzing request (repeatable, order matters)'
complete -c ffuf -o postflight-var -d 'Extract a variable from the preceding -postflight response: "NAME:regex" (repeatable)'
complete -c ffuf -o preflight -d 'Raw HTTP request file to run before each fuzzing request (repeatable, order matters)'
complete -c ffuf -o preflight-error -d 'Preflight error handling: "abort" or "ignore" (default: abort)'
complete -c ffuf -o preflight-mode -d 'Preflight execution mode: "per-request" or "per-thread" (default: per-request)'
complete -c ffuf -o preflight-var -d 'Extract a variable from the preceding -preflight response: "NAME:regex" (repeatable)'
complete -c ffuf -o r -d 'Follow redirects (default: false)'
complete -c ffuf -o raw -d 'Do not encode URI (default: false)'
complete -c ffuf -o recursion -d 'Scan recursively. Only FUZZ keyword is supported, and URL (-u) has to end in it. (default: false)'
complete -c ffuf -o recursion-depth -d 'Maximum recursion depth. (default: 0)'
complete -c ffuf -o recursion-strategy -d 'Recursion strategy: "default" for a redirect based, and "greedy" to recurse on all matches (default: default)'
complete -c ffuf -o replay-proxy -d 'Replay matched requests using this proxy'
complete -c ffuf -o sni -d 'Target TLS SNI, does not support FUZZ keyword'
complete -c ffuf -o timeout -d 'HTTP request timeout in seconds (default: 10)'
complete -c ffuf -o u -d 'Target URL'
complete -c ffuf -o x -d 'Proxy URL (SOCKS5 or HTTP)'

# GENERAL OPTIONS
complete -c ffuf -o V -d 'Show version information'
complete -c ffuf -o ac -d 'Automatically calibrate filtering options (default: false)'
complete -c ffuf -o acc -d 'Custom auto-calibration string. Can be used multiple times. Implies -ac'
complete -c ffuf -o ach -d 'Per host autocalibration (default: false)'
complete -c ffuf -o ack -d 'Autocalibration keyword (default: FUZZ)'
complete -c ffuf -o acs -d 'Custom auto-calibration strategies. Can be used multiple times. Implies -ac'
complete -c ffuf -o c -d 'Colorize output. (default: false)'
complete -c ffuf -o config -d 'Load configuration from a file'
complete -c ffuf -o json -d 'JSON output, printing newline-delimited JSON records (default: false)'
complete -c ffuf -o maxtime -d 'Maximum running time in seconds for entire process. (default: 0)'
complete -c ffuf -o maxtime-job -d 'Maximum running time in seconds per job. (default: 0)'
complete -c ffuf -o noninteractive -d 'Disable the interactive console functionality (default: false)'
complete -c ffuf -o p -d 'Seconds of delay between requests, or a range of random delay. For example "0.1" or "0.1-2.0"'
complete -c ffuf -o rate -d 'Rate of requests per second (default: 0)'
complete -c ffuf -o s -d 'Do not print additional information (silent mode) (default: false)'
complete -c ffuf -o sa -d 'Stop on all error cases. Implies -sf and -se. (default: false)'
complete -c ffuf -o scraperfile -d 'Custom scraper file path'
complete -c ffuf -o scrapers -d 'Active scraper groups (default: all)'
complete -c ffuf -o se -d 'Stop on spurious errors (default: false)'
complete -c ffuf -o search -d 'Search for a FFUFHASH payload from ffuf history'
complete -c ffuf -o sf -d 'Stop when > 95% of responses return 403 Forbidden (default: false)'
complete -c ffuf -o t -d 'Number of concurrent threads. (default: 40)'
complete -c ffuf -o v -d 'Verbose output'

# MATCHER OPTIONS
complete -c ffuf -o mc -d 'Match HTTP status codes, or "all" for everything'
complete -c ffuf -o ml -d 'Match amount of lines in response'
complete -c ffuf -o mmode -d 'Matcher set operator. Either of: and, or'
complete -c ffuf -o mr -d 'Match regexp'
complete -c ffuf -o ms 'Match HTTP response size'
complete -c ffuf -o mt -d 'Match how many milliseconds to the first response byte, either greater or less than. EG: >100 or <100'
complete -c ffuf -o mw -d 'Match amount of words in response'

# FILTER OPTIONS
complete -c ffuf -o fc -d 'Filter HTTP status codes from response. Comma separated list of codes and ranges'
complete -c ffuf -o fl -d 'Filter by amount of lines in response. Comma separated list of line counts and ranges'
complete -c ffuf -o fmode -d 'Filter set operator. Either of: and, or'
complete -c ffuf -o fr -d 'Filter regexp'
complete -c ffuf -o fs -d 'Filter HTTP response size. Comma separated list of sizes and ranges'
complete -c ffuf -o ft -d 'Filter by number of milliseconds to the first response byte, either greater or less than. EG: >100 or <100'
complete -c ffuf -o fw -d 'Filter by amount of words in response. Comma separated list of word counts and ranges'

# INPUT OPTIONS
complete -c ffuf -o D -d 'DirSearch wordlist compatibility mode. Used in conjunction with -e flag. (default: false)'
complete -c ffuf -o e -d 'Comma separated list of extensions. Extends FUZZ keyword'
complete -c ffuf -o enc -d 'Encoders for keywords, eg. FUZZ:urlencode b64encode'
complete -c ffuf -o ic -d 'Ignore wordlist comments (default: false)'
complete -c ffuf -o input-cmd -d 'Command producing the input. --input-num is required when using this input method. Overrides -w'
complete -c ffuf -o input-num -d 'Number of inputs to test. Used in conjunction with --input-cmd. (default: 100)'
complete -c ffuf -o input-shell -d 'Shell to be used for running command'
complete -c ffuf -o mode -d 'Multi-wordlist operation mode. Available modes: clusterbomb, pitchfork, sniper (default: clusterbomb)'
complete -c ffuf -o request -d 'File containing the raw http request'
complete -c ffuf -o request-proto -d 'Protocol to use along with raw request (default: https)'
complete -c ffuf -o w -d 'Wordlist file path and (optional) keyword separated by colon. eg. \'/path/to/wordlist:KEYWORD\''

# OUTPUT OPTIONS
complete -c ffuf -o audit-log -d 'Write audit log containing all requests, responses and config'
complete -c ffuf -o debug-log -d 'Write all of the internal logging to the specified file'
complete -c ffuf -o o -d 'Write output to file'
complete -c ffuf -o od -d 'Directory path to store matched results to'
complete -c ffuf -o of -d 'Output file format' -a 'json, ejson, html, md, csv, ecsv, all'
complete -c ffuf -o or -d 'Don\'t create the output file if we don\'t have results'
