complete -c php -s a -d "Run as interactive shell (requires readline extension)"
complete -c php -s c -r -d "Look for php.ini file in this directory"
complete -c php -s n -d "No configuration (ini) files will be used"
complete -c php -s d -x -d "Define a php entry (foo[=bar])"
complete -c php -s e -d "Generate extended information for debugger/profiler"
complete -c php -s f -r -d "Parse and execute a file"
complete -c php -s h -d "Display help message"
complete -c php -s i -d "PHP information"
complete -c php -s l -d "Syntax check only (lint)"
complete -c php -s m -d "Show compiled in modules"
complete -c php -s r -x -d "Run PHP code without using script tags <?..?>"
complete -c php -s B -x -d "Run PHP begin_code before processing input lines"
complete -c php -s R -x -d "Run PHP code for every input line"
complete -c php -s F -r -d "Parse and execute a file for every input line"
complete -c php -s E -x -d "Run PHP end_code after processing all input lines"
complete -c php -s H -d "Hide any passed arguments from external tools"
complete -c php -s S -x -d "Run with built-in web server"
complete -c php -s t -x -a "(__fish_complete_directories)" -d "Specify document root <docroot> for built-in web server"
complete -c php -s s -d "Output HTML syntax highlighted source"
complete -c php -s v -d "Version number"
complete -c php -s w -d "Output source with stripped comments and whitespace"
complete -c php -l ini -d "Show configuration file names (=diff to show differences)"
complete -c php -l rf -x -d "Show information about a function"
complete -c php -l rc -x -d "Show information about a class"
complete -c php -l re -x -d "Show information about a extension"
complete -c php -l rz -x -d "Show information about a Zend extension"
complete -c php -l ri -x -d "Show configuration for an extension"
complete -c php -s z -d ""
